---
- name: Install dependencies for awscli
  apt:
    name: "python3-pip"
    state: latest
    update_cache: yes
    
- name: Remove awscli   #for testing handlers
  pip:
    name: "awscli"
    executable: pip3
    state: absent 

- name: Install awscli with pip3
  pip:
    name: "awscli"
    executable: pip3
  notify:
    - "Notify that aws is installed"

- name: install cloudwatch agent
  apt:
    deb: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
  notify:
    - "Run cloudwatch as a service"


