version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    networks:
      app_net:
        ipv4_address: 10.0.0.2
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      app_net:
        ipv4_address: 10.0.0.3
    expose:
      - 5432
volumes:
  postgres_data:


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1
